title = "Tom Kimpson"
baseURL = "https://tomkimpson.github.io"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = true          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Olivier Roques"
  description = "A simple monospaced resume theme for Hugo."
  favicon = "/favicon.png"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "Developed using Hugo-researcher"
    url = "https://github.com/ojroques/hugo-researcher"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "avenir" #avenir
    fontSize = "14pt"
    pageWidth = "750px"
    avatarSize = "200px"
    colorBlack = "#222222"
    colorRed = "#107896"
  [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/tomkimpson/"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:tom.kimpson@unimelb.edu.au"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "Scholar"
    url = "https://github.com/tomkimpson"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "*"
    url = "/"
    weight = 1

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
